wandb_version: 1

seed:
  desc: null
  value: 42
num_exp:
  desc: null
  value: 50000
in_features:
  desc: null
  value: 10
latent_dim:
  desc: null
  value: 4
output_dim:
  desc: null
  value: 2
val_split:
  desc: null
  value: 0.2
task_type:
  desc: null
  value: regression
hierarch_net:
  desc: null
  value: true
GAM_block_layers_type_phase1:
  desc: null
  value: ReLU
GAM_block_layers_type_phase2:
  desc: null
  value: Monotonic
featureNN_arch_phase1:
  desc: null
  value: multi_output
featureNN_arch_phase2:
  desc: null
  value: multi_output
first_activate_layer_phase1:
  desc: null
  value: ReLU
first_activate_layer_phase2:
  desc: null
  value: LipschitzMonotonic
first_hidden_dim_phase1:
  desc: null
  value: 64
first_hidden_dim_phase2:
  desc: null
  value: 128
shallow_phase1:
  desc: null
  value: false
shallow_phase2:
  desc: null
  value: false
hidden_activate_layer_phase1:
  desc: null
  value: ReLU
hidden_activate_layer_phase2:
  desc: null
  value: LipschitzMonotonic
hidden_dim_phase1:
  desc: null
  value:
  - 64
  - 32
hidden_dim_phase2:
  desc: null
  value:
  - 128
  - 64
hidden_dropout_phase1:
  desc: null
  value: 0.2
hidden_dropout_phase2:
  desc: null
  value: 0.0
feature_dropout_phase1:
  desc: null
  value: 0.3
feature_dropout_phase2:
  desc: null
  value: 0.0
weight_norms_kind_phase1:
  desc: null
  value: one-inf
weight_norms_kind_phase2:
  desc: null
  value: one-inf
group_size_phase1:
  desc: null
  value: 2
group_size_phase2:
  desc: null
  value: 2
monotonic_constraint_phase1:
  desc: null
  value: null
monotonic_constraint_phase2:
  desc: null
  value: null
epochs:
  desc: null
  value: 2000
batch_size:
  desc: null
  value: 1024
learning_rate:
  desc: null
  value: 0.0035
weight_decay:
  desc: null
  value: 0.0001
clip_value:
  desc: null
  value: 0
l2_lambda_phase1:
  desc: null
  value: 0.0
l2_lambda_phase2:
  desc: null
  value: 0.0
l1_lambda_phase1:
  desc: null
  value: 0.0
l1_lambda_phase2:
  desc: null
  value: 0.0
monotonicity_lambda:
  desc: null
  value: 0.0
eval_every:
  desc: null
  value: 1
early_stop_delta:
  desc: null
  value: 0.0
early_stop_patience:
  desc: null
  value: 200
optimizer:
  desc: null
  value: Adam
lr_scheduler:
  desc: null
  value: NoScheduler
rop_mode:
  desc: null
  value: min
rop_factor:
  desc: null
  value: 0.2
rop_patience:
  desc: null
  value: 10
rop_threshold:
  desc: null
  value: 0.001
rop_threshold_mode:
  desc: null
  value: abs
base_lr:
  desc: null
  value: 0.001
max_lr:
  desc: null
  value: 0.01
div_factor:
  desc: null
  value: 25
final_div_factor:
  desc: null
  value: 10000.0
n_cycles:
  desc: null
  value: 5
cycle_momentum:
  desc: null
  value: false
pct_step_up:
  desc: null
  value: 0.3
save_results:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.8.8
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726555048
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 3
      - 16
      - 23
      4: 3.8.8
      5: 0.17.9
      8:
      - 5
      13: linux-x86_64
